language: node_js
node_js:
  - node
  - 8
  - 10
  - 12
script:
  - export NODE_ENV=test
  - npm run build
  - npm run test
  - npm run lint
  - nyc --silent npm run test
  - nyc report --reporter=text-lcov | coveralls
  - nyc check-coverage --lines 70
after_success:
  -
notifications:
  email: false
sudo: false